title: Об'єктно-орієнтоване програмування
description: Виконання завдань з навчальної дисципліни "Об'єктно-орієнтоване програмування" 
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
