title: Об'єктно-орієнтоване програмування
description: Виконання завдань з навчальної дисципліни "Об'єктно-орієнтоване програмування" 
theme: jekyll-theme-hacker
remote_theme: midnight
plugins:
- jekyll-remote-theme
